---
swagger: '2.0'
info:
  description: Flotta backend API for remote data storage
  title: Flotta backend API
  version: 1.0.0
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
basePath: /api/flotta-backend/v1
definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  device-configuration-response:
    type: object
    properties:
      message:
        type: string
      device-configuration:
        $ref: 'swagger.yaml/#definitions/device-configuration'
  device-registration-status-response:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
paths:
  '/namespaces/{namespace}/devices/{device-id}/configuration':
    get:
      description: Returns the device configuration
      operationId: GetDeviceConfiguration
      parameters:
        - in: path
          name: namespace
          description: Namespace where the device resides
          type: string
          required: true
        - in: path
          name: device-id
          description: Device ID
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/device-configuration-response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        default:
          description: Error
          schema:
            $ref: '#/definitions/device-configuration-response'
  '/namespaces/{namespace}/devices/{device-id}/enrolment':
    post:
      description: Initiates the process of enrolling the device
      operationId: EnrolDevice
      parameters:
        - in: path
          name: namespace
          description: Namespace where the device resides
          type: string
          required: true
        - in: path
          name: device-id
          description: Device ID
          type: string
          required: true
        - in: body
          name: enrolment-info
          required: true
          schema:
            $ref: 'swagger.yaml/#definitions/enrolment-info'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        default:
          description: Error
          schema:
            $ref: '#/definitions/error'
  '/namespaces/{namespace}/devices/{device-id}/registration':
    get:
      description: >-
        Returns a device registration status, which can be registered,
        unregistered or unknown.
      operationId: GetRegistrationStatus
      parameters:
        - in: path
          name: namespace
          description: Namespace where the device resides
          type: string
          required: true
        - in: path
          name: device-id
          description: Device ID
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/device-registration-status-response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Error
    put:
      description: Registers the device by providing its hardware configuration
      operationId: RegisterDevice
      parameters:
        - in: path
          name: namespace
          description: Namespace where the device resides
          type: string
          required: true
        - in: path
          name: device-id
          description: Device ID
          type: string
          required: true
        - in: body
          name: registration-info
          required: true
          schema:
            $ref: 'swagger.yaml/#definitions/registration-info'
      responses:
        '200':
          description: Updated
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        default:
          description: Error
          schema:
            $ref: '#/definitions/error'
  '/namespaces/{namespace}/devices/{device-id}/heartbeat':
    put:
      description: Updates the heartbeat information of the device.
      operationId: UpdateHeartBeat
      parameters:
        - in: path
          name: namespace
          description: Namespace where the device resides
          type: string
          required: true
        - in: path
          name: device-id
          description: Device ID
          type: string
          required: true
        - in: body
          name: heartbeat
          required: true
          schema:
            $ref: 'swagger.yaml/#definitions/heartbeat'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Error
