swagger: '2.0'
info:
  description: 'Kube for Edge Management'
  version: 1.0.0
  title: Kube4EdgeManagement
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/k4e-management/v1
tags:
  - name: devices
    description: Device management


schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  agentAuth:
    type: apiKey
    in: header
    name: X-Secret-Key

paths:
  /device/{device_id}:
    get:
      operationId: GetDeviceConfiguration
      security:
        - agentAuth: []
      tags:
        - devices
      parameters:
        - in: path
          name: device_id
          description: Device to get configuration for
          type: string
          required: true
      responses:
        "200":
          description: Success.
          schema:
            $ref: '#/definitions/workload-list'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden.
        "404":
          description: Error.
        "500":
          description: Error.


definitions:
  workload-list:
    type: object
    properties:
      device_id:
        type: string
        description: Device identifier

