swagger: '2.0'
info:
  description: 'Kube for Edge Management'
  version: 1.0.0
  title: Kube4EdgeManagement
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/k4e-management/v1
tags:
  - name: devices
    description: Device management

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  agentAuth:
    type: apiKey
    in: header
    name: X-Secret-Key

paths:
  /device/register:
    post:
      operationId: RegisterDevice
      security:
        - agentAuth: []

      tags:
        - devices
      parameters:
        - name: registration-info
          in: body
          description: Device registration information
          required: true
          schema:
           $ref: '#/definitions/registration-info'
      responses:
        "200":
          description: Success.
          schema:
            $ref: '#/definitions/registration-confirmation'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /device/{device_id}:
    get:
      operationId: GetDeviceConfiguration
      security:
        - agentAuth: []
      tags:
        - devices
      parameters:
        - in: path
          name: device_id
          description: Device to get configuration for
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/device-configuration'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

definitions:
  device-configuration:
    type: object
    properties:
      device_id:
        type: string
        description: Device identifier
      workloads:
        $ref: '#/definitions/workload-list'
        description: List of workloads deployed to the device

  workload-list:
    type: array
    items:
      $ref: '#/definitions/workload'

  workload:
    type: object
    properties:
      name:
        type: string
        description: Name of the workload
        
  registration-info:
    type: object
    properties:
      os_image_id:
        type: string
      hardware:
        description: Hardware information
        $ref:  '#/definitions/hardware-info'

  hardware-info:
    type: object
    properties:
      hostname:
        type: string
      cpu:
        $ref: '#/definitions/cpu'
      memory:
        $ref: '#/definitions/memory'

  memory:
    type: object
    properties:
      physical_bytes:
        type: integer
      usable_bytes:
        type: integer

  cpu:
    type: object
    properties:
      count:
        type: integer
      frequency:
        type: number
      flags:
        type: array
        items:
          type: string
      model_name:
        type: string
      architecture:
        type: string

  registration-confirmation:
    type: object
    properties:
      id:
        type: string
        