swagger: '2.0'
info:
  description: 'Kube for Edge Management'
  version: 1.0.0
  title: Kube4EdgeManagement
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/k4e-management/v1
tags:
  - name: devices
    description: Device management

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  agentAuth:
    type: apiKey
    in: header
    name: X-Secret-Key

paths:
  /data/{device_id}/in:
    get:
      operationId: GetDataMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/message'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /data/{device_id}/out:
    post:
      operationId: PostDataMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
        - in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/message'
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /control/{device_id}/in:
    get:
      operationId: GetControlMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/message'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /control/{device_id}/out:
    post:
      operationId: PostControlMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
        - in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/message'
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

definitions:
  device-configuration-message:
    type: object
    properties:
      device_id:
        type: string
        description: Device identifier
      version:
        type: string
      configuration:
        $ref: '#/definitions/device-configuration'
      workloads:
        $ref: '#/definitions/workload-list'
        description: List of workloads deployed to the device

  device-configuration:
    type: object
    properties:
      heartbeat:
        $ref: '#/definitions/heartbeat-configuration'

  heartbeat-configuration:
    type: object
    properties:
      period_seconds:
        type: integer
      hardware_profile:
        $ref: '#/definitions/hardware-profile-configuration'

  hardware-profile-configuration:
    type: object
    properties:
      include:
        type: boolean
      scope:
        type: string
        enum:
          - full
          - delta

  workload-list:
    type: array
    items:
      $ref: '#/definitions/workload'

  workload:
    type: object
    properties:
      name:
        type: string
        description: Name of the workload
      version:
        type: string
        
  registration-info:
    type: object
    properties:
      os_image_id:
        type: string
      hardware:
        description: Hardware information
        $ref:  '#/definitions/hardware-info'

  hardware-info:
    type: object
    properties:
      hostname:
        type: string
      cpu:
        $ref: '#/definitions/cpu'
      memory:
        $ref: '#/definitions/memory'

  memory:
    type: object
    properties:
      physical_bytes:
        type: integer
      usable_bytes:
        type: integer

  cpu:
    type: object
    properties:
      count:
        type: integer
      frequency:
        type: number
      flags:
        type: array
        items:
          type: string
      model_name:
        type: string
      architecture:
        type: string

  heartbeat:
    type: object
    properties:
      device_id:
        type: string
      time:
        type: string
        format: date-time
      status:
        type: string
        enum:
          - up
          - degraded
      version:
        type: string
      workloads:
        type: array
        items:
          $ref: '#/definitions/workload-status'

  workload-status:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
        enum:
          - deploying
          - running
          - crashed
          - stopped

  message:
    type: object
    properties:
      type:
        type: string
        enum:
          - connection-status
          - command
          - event
          - data
      message_id:
        type: string
      response_to:
        type: string
      version:
        type: integer
      sent:
        type: string
        format: date-time
      directive:
        type: string
      metadata:
        type: object
      content:
        description: Content
