---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: flotta-controller-manager
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app: flotta-controller-manager
spec:
  selector:
    matchLabels:
      app: flotta-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: flotta-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        envFrom:
        - configMapRef:
            name: manager-config
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
          - containerPort: 8043
            name: yggds
          - containerPort: 8080
            name: metrics
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: controller-manager
  namespace: system
  labels:
    app: flotta-controller-manager
spec:
  ports:
    - name: yggds
      protocol: TCP
      port: 8043
      targetPort: yggds
  selector:
    app: flotta-controller-manager
  type: ClusterIP
