// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/project-flotta/flotta-operator/internal/common/repository/endnodeautoconfig (interfaces: Repository)

// Package endnodeautoconfig is a generated GoMock package.
package endnodeautoconfig

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"

	v1alpha1 "github.com/project-flotta/flotta-operator/api/v1alpha1"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 *v1alpha1.EndNodeAutoConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// GetByDevice mocks base method.
func (m *MockRepository) GetByDevice(arg0 context.Context, arg1, arg2 string) (*v1alpha1.EndNodeAutoConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDevice", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.EndNodeAutoConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDevice indicates an expected call of GetByDevice.
func (mr *MockRepositoryMockRecorder) GetByDevice(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDevice", reflect.TypeOf((*MockRepository)(nil).GetByDevice), arg0, arg1, arg2)
}

// ListByDevice mocks base method.
func (m *MockRepository) ListByDevice(arg0 context.Context, arg1, arg2 string) ([]*v1alpha1.EndNodeAutoConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDevice", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*v1alpha1.EndNodeAutoConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDevice indicates an expected call of ListByDevice.
func (mr *MockRepositoryMockRecorder) ListByDevice(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDevice", reflect.TypeOf((*MockRepository)(nil).ListByDevice), arg0, arg1, arg2)
}

// ListByNamespace mocks base method.
func (m *MockRepository) ListByNamespace(arg0 context.Context, arg1 string) ([]*v1alpha1.EndNodeAutoConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNamespace", arg0, arg1)
	ret0, _ := ret[0].([]*v1alpha1.EndNodeAutoConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNamespace indicates an expected call of ListByNamespace.
func (mr *MockRepositoryMockRecorder) ListByNamespace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNamespace", reflect.TypeOf((*MockRepository)(nil).ListByNamespace), arg0, arg1)
}

// ListForSelector mocks base method.
func (m *MockRepository) ListForSelector(arg0 context.Context, arg1 *v1.LabelSelector, arg2 string) ([]v1alpha1.EndNodeAutoConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForSelector", arg0, arg1, arg2)
	ret0, _ := ret[0].([]v1alpha1.EndNodeAutoConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForSelector indicates an expected call of ListForSelector.
func (mr *MockRepositoryMockRecorder) ListForSelector(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForSelector", reflect.TypeOf((*MockRepository)(nil).ListForSelector), arg0, arg1, arg2)
}

// Patch mocks base method.
func (m *MockRepository) Patch(arg0 context.Context, arg1, arg2 *v1alpha1.EndNodeAutoConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockRepositoryMockRecorder) Patch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockRepository)(nil).Patch), arg0, arg1, arg2)
}

// PatchStatus mocks base method.
func (m *MockRepository) PatchStatus(arg0 context.Context, arg1 *v1alpha1.EndNodeAutoConfig, arg2 *client.Patch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchStatus indicates an expected call of PatchStatus.
func (mr *MockRepositoryMockRecorder) PatchStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchStatus", reflect.TypeOf((*MockRepository)(nil).PatchStatus), arg0, arg1, arg2)
}

// Read mocks base method.
func (m *MockRepository) Read(arg0 context.Context, arg1, arg2 string) (*v1alpha1.EndNodeAutoConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.EndNodeAutoConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockRepositoryMockRecorder) Read(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockRepository)(nil).Read), arg0, arg1, arg2)
}

// RemoveFinalizer mocks base method.
func (m *MockRepository) RemoveFinalizer(arg0 context.Context, arg1 *v1alpha1.EndNodeAutoConfig, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFinalizer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFinalizer indicates an expected call of RemoveFinalizer.
func (mr *MockRepositoryMockRecorder) RemoveFinalizer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFinalizer", reflect.TypeOf((*MockRepository)(nil).RemoveFinalizer), arg0, arg1, arg2)
}
