# permissions for end users to edit edgedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedeployment-editor-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedeployments/status
  verbs:
  - get
