# permissions for end users to edit edgedevicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevicegroup-editor-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevicegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevicegroups/status
  verbs:
  - get
