# permissions for end users to view edgedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedeployment-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedeployments/status
  verbs:
  - get
