# permissions for end users to edit endnodeautoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endnodeautoconfig-editor-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - endnodeautoconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - endnodeautoconfigs/status
  verbs:
  - get
