apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager
  namespace: system
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: k4e-operator-controller-manager
    weight: 100
  wildcardPolicy: None
