apiVersion: management.k4e.io/v1alpha1
kind: EdgeDeployment
metadata:
  name: edgedeployment-sample
spec:
  device: 114c56c6-6620-43e3-a541-dac21dfca36b
  type: pod
  pod:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              hostPort: 9090

