// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WirelessDevice wireless device
//
// swagger:model wireless_device
type WirelessDevice struct {

	// device properties
	DeviceProperties []*DeviceProperty `json:"device_properties"`

	// Online status of the end device; Online/offline
	WirelessDeviceAvailability string `json:"wireless_device_availability,omitempty"`

	// Battery percentage of the end device; otherwise null
	WirelessDeviceBattery string `json:"wireless_device_battery,omitempty"`

	// Communication method used by the end node device. Zigbee, Wi-Fi, BLE, Zigbee etc.
	WirelessDeviceConnection string `json:"wireless_device_connection,omitempty"`

	// if end node device is a sensor, JSON format data will be here otherwise will be null
	WirelessDeviceDescription string `json:"wireless_device_description,omitempty"`

	// unique identifier for device e.g. Serial number
	WirelessDeviceIdentifier string `json:"wireless_device_identifier,omitempty"`

	// The last time the end node transacted
	WirelessDeviceLastSeen string `json:"wireless_device_last_seen,omitempty"`

	// Device Manufacturer of the end node
	WirelessDeviceManufacturer string `json:"wireless_device_manufacturer,omitempty"`

	// Model number/string of the end node device
	WirelessDeviceModel string `json:"wireless_device_model,omitempty"`

	// Friendly name of the device.
	WirelessDeviceName string `json:"wireless_device_name,omitempty"`

	// Transfer protocol used by the end node device. MQTT, HTTP, COAP etc.
	WirelessDeviceProtocol string `json:"wireless_device_protocol,omitempty"`

	// Software version of the end node device
	WirelessDeviceSwVersion string `json:"wireless_device_sw_version,omitempty"`
}

// Validate validates this wireless device
func (m *WirelessDevice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceProperties(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WirelessDevice) validateDeviceProperties(formats strfmt.Registry) error {
	if swag.IsZero(m.DeviceProperties) { // not required
		return nil
	}

	for i := 0; i < len(m.DeviceProperties); i++ {
		if swag.IsZero(m.DeviceProperties[i]) { // not required
			continue
		}

		if m.DeviceProperties[i] != nil {
			if err := m.DeviceProperties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("device_properties" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("device_properties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this wireless device based on the context it is used
func (m *WirelessDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeviceProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WirelessDevice) contextValidateDeviceProperties(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DeviceProperties); i++ {

		if m.DeviceProperties[i] != nil {
			if err := m.DeviceProperties[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("device_properties" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("device_properties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WirelessDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WirelessDevice) UnmarshalBinary(b []byte) error {
	var res WirelessDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
